
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package test.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int ADD = 2;
  public static final int MINUS = 3;
  public static final int DIV = 5;
  public static final int DECIMAL = 7;
  public static final int TIMES = 4;
  public static final int EOF = 0;
  public static final int ENTERO = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ADD",
  "MINUS",
  "TIMES",
  "DIV",
  "ENTERO",
  "DECIMAL"
  };
}

